DOC: Update license headers
libAtoms/matscipy pull request #82
Opened 2021-07-29 16:35 UTC by pastewka

This PR adds maintenance script that update the license headers with the information on who modified the file when, pulled from the git log.

2021-07-29 16:36 UTC, pastewka commented
Hi @jameskermode - this is an attempt to make the author information a bit more egalitarian. Please have a look and see if you like it. I could not identify who "Montmorency" is, have a look at the `AUTHORS` file.

2021-07-29 18:22 UTC, jameskermode commented
Thanks for doing this. Will check it carefully next week (I’m on holiday this week.)

2021-08-02 09:00 UTC, jameskermode requested changes
Looks great - apart from adding Henry's name I don't see any other errors or omissions. Thanks again for doing this.

2021-08-02 10:49 UTC, pastewka commented on AUTHORS
> +Montmorency <lamberh@tcd.ie>
Sounds good, I just added his name

2021-08-02 10:52 UTC, pastewka commented
Hi @jameskermode - comments should be addressed

2021-08-02 10:53 UTC, jameskermode approved these changes

2021-08-02 10:53 UTC, merged